package exception;

import java.util.Scanner;

public class Test2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner input = new Scanner(System.in);
		int result = 0;
		try{
			int a = input.nextInt();
			int b = input.nextInt();
			result = a/b;
		}catch(Exception e){
			System.out.println("出错了");
		}
		
		System.out.println(result);
				
	}

}
